//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public int AuditTrailID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TableName { get; set; }
        public string AuditDate { get; set; }
        public string OldValue { get; set; }
        public string AuditType { get; set; }
        public string NewValue { get; set; }
        public byte[] AuditDescription { get; set; }
    
        public virtual User User { get; set; }
    }
}
