//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Company_ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Contact_Number { get; set; }
        public string Email_Address { get; set; }
        public string Telephone_Number { get; set; }
    }
}
