//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int Delivery_ID { get; set; }
        public Nullable<int> Address_ID { get; set; }
        public Nullable<int> Customer_Order_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> OrderStatus_ID { get; set; }
    
        public virtual Customer_Order Customer_Order { get; set; }
        public virtual Delivery_Address Delivery_Address { get; set; }
        public virtual Order_Status Order_Status { get; set; }
    }
}
