//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Design_Line
    {
        public int Design_Line_ID { get; set; }
        public Nullable<int> Design_ID { get; set; }
        public Nullable<int> Template_Position_ID { get; set; }
        public Nullable<int> Job_Type_ID { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public string Image { get; set; }
        public string Text { get; set; }
    
        public virtual Design Design { get; set; }
        public virtual Job_Type Job_Type { get; set; }
        public virtual Template_Position Template_Position { get; set; }
    }
}
