//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TshidiDatabaseEntities : DbContext
    {
        public TshidiDatabaseEntities()
            : base("name=TshidiDatabaseEntities")
        {
            base.Configuration.ProxyCreationEnabled = false;
            base.Configuration.LazyLoadingEnabled = false;
                }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditTrail> AuditTrails { get; set; }
        public virtual DbSet<Capture_Collect> Capture_Collect { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_Order> Customer_Order { get; set; }
        public virtual DbSet<Customer_Order_Line> Customer_Order_Line { get; set; }
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<Delivery_Address> Delivery_Address { get; set; }
        public virtual DbSet<Design> Designs { get; set; }
        public virtual DbSet<Design_Line> Design_Line { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Job_Type> Job_Type { get; set; }
        public virtual DbSet<Order_Status> Order_Status { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Permission_Line> Permission_Line { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Product_Category> Product_Category { get; set; }
        public virtual DbSet<Product_Size> Product_Size { get; set; }
        public virtual DbSet<Product_Type> Product_Type { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<Quotation_Line> Quotation_Line { get; set; }
        public virtual DbSet<Quotation_Request> Quotation_Request { get; set; }
        public virtual DbSet<Quotation_Request_Line> Quotation_Request_Line { get; set; }
        public virtual DbSet<Quotation_Status> Quotation_Status { get; set; }
        public virtual DbSet<Return_Customer_Order> Return_Customer_Order { get; set; }
        public virtual DbSet<Return_Customer_Order_Line> Return_Customer_Order_Line { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Supplier_Order> Supplier_Order { get; set; }
        public virtual DbSet<Supplier_Order_Line> Supplier_Order_Line { get; set; }
        public virtual DbSet<Supplier_Order_Status> Supplier_Order_Status { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<Template_Position> Template_Position { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
        public virtual DbSet<Web_Link> Web_Link { get; set; }
    }
}
