//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Order_Line
    {
        public int Supplier_Order_Line_ID { get; set; }
        public Nullable<int> Product_Type_ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Supplier_Order_ID { get; set; }
        public Nullable<int> Customer_Order_Line_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
    
        public virtual Customer_Order_Line Customer_Order_Line { get; set; }
        public virtual Product_Type Product_Type { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Supplier_Order Supplier_Order { get; set; }
    }
}
