//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template_Position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Template_Position()
        {
            this.Design_Line = new HashSet<Design_Line>();
        }
    
        public int Template_Position_ID { get; set; }
        public Nullable<int> Position_ID { get; set; }
        public Nullable<int> Template_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Design_Line> Design_Line { get; set; }
        public virtual Position Position { get; set; }
        public virtual Template Template { get; set; }
    }
}
